# Generated by Django 3.2.23 on 2023-11-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0005_booking_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
