# Generated by Django 3.2.23 on 2023-11-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0006_alter_booking_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='title',
        ),
    ]
