# Generated by Django 3.2.23 on 2023-12-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0007_remove_booking_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamp',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
