# Generated by Django 3.2.23 on 2023-12-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0010_remove_comment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
    ]
