# Generated by Django 3.2.23 on 2023-12-22 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0012_post_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestamp',
            name='booked',
        ),
    ]
